- name: default configuration
  hosts: linux
  become: true

  tasks:

  - name: timezone
    command: timedatectl set-timezone Europe/Amsterdam
  
  - name: ncdu
    apt:
      name: ncdu
      state: latest

  - name: net-tools
    apt:
      name: net-tools
      state: latest

  - name: ca-certificates
    apt:
      name: ca-certificates
      state: latest

  - name: curl
    apt:
      name: curl
      state: latest

  - name: gnupg
    apt:
      name: gnupg
      state: latest

  - name: lsb-release
    apt:
      name: lsb-release
      state: latest

  - name: software-properties-common
    apt:
      name: software-properties-common
      state: latest

  - name: snmpd
    apt:
      name: snmpd
      state: latest

  - name: remove gpg
    file: 
      path: /usr/share/keyrings/docker-archive-keyring.gpg
      state: absent

  - name: add gpg key
    shell:  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: install prerequisites
    command: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
  - name: update cache
    apt: 
      update_cache: yes

  - name: docker-ce
    apt:
      name: docker-ce
      state: latest

  - name: docker-ce-cli
    apt:
      name: docker-ce-cli
      state: latest

  - name: containerd.io
    apt:
      name: containerd.io
      state: latest

  - name: samba
    apt:
      name: samba
      state: latest

  - name: install docker compose
    shell: |
      curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose

  - name: remove default snmpd config file
    file:
      path: /etc/snmp/snmpd.conf
      state: absent

  - name: add snpmd config
    copy:
      dest: /etc/snmp/snmpd.conf
      content: rocommunity joe

  - name: docker folder
    file:
      path: /docker
      state: directory
      mode: '770'
      owner: 'hwadmin'
      group: 'docker'

  - name: joe
    file:
      path: /joe
      state: directory
